import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import SearchForm from "@/components/SearchForm";
import WordInfoSheet from "@/components/WordInfoSheet";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white h-full`}
      >
        <div className="flex h-full">
          <main className="flex-1 max-w-screen-xl mx-auto p-4 md:p-8">
            <div className="flex flex-col h-full gap-8 items-center">
              <Card className="w-full lg:w-2/3">
                <CardHeader>
                  <CardTitle className="text-center">
                    Search Wiktionary
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <SearchForm />
                </CardContent>
              </Card>

              <Card className="flex-1 flex flex-col min-h-0 w-full">
                <CardHeader className="shrink-0">
                  <CardTitle className="text-center">Etymology Tree</CardTitle>
                </CardHeader>
                <CardContent className="flex-1 overflow-y-auto p-4">
                  {children}
                </CardContent>
              </Card>
            </div>
          </main>

          <WordInfoSheet className="min-w-[50vw] border-l border-gray-300 p-8 overflow-y-auto" />
        </div>
      </body>
    </html>
  );
}
